name: Build and Deploy WebGL

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2022.3.11f1-webgl-1.0.0
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build WebGL
      run: |
        unity-editor -batchmode -nographics -projectPath . -buildTarget WebGL -quit
    
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: webgl-build
        path: WebGL-Build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download build
      uses: actions/download-artifact@v4
      with:
        name: webgl-build
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./